### ISSUE TITLE
Not syncing in the new update and it works when i revert to the old version

### ISSUE THREAD

**Issue by 22arun11** [arunbhardwaj/LeetHub-2.0#12]
i just installed the extension and the extension seems to works fine only when i revert back to the old version and it doesnt work if i use it in the new version

**Comment by arunachalamev** [comment]
+1 It doesnt work as on 07/14 Leetcode changes in the UI

**Comment by jaydeep-pro** [comment]
yes Please update it , it doesnt work on new leetcode ui, On 13th july 2023

**Comment by umadan-dev** [comment]
same issue

**Comment by bjpfox** [comment]
I'm having the same issue - it was working fine previously but has suddenly stopped working.

**Comment by arunbhardwaj** [comment]
Thank you for the notification and apologies for the wait. I was on vacation when this happened. I just fixed the issue through PR #18. Please update your extension to receive the fix!
