### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by bharat407** [arunbhardwaj/LeetHub-2.0#13]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
Whenever I submit a code on LeetCode after successful submission LeetHub v2 not working properly not make commit to the GitHub repo and does no sync it happens a lot of time pls view this problem and make correct 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by nano-bot01** [comment]
![image](https://github.com/arunbhardwaj/LeetHub-2.0/assets/78251168/fc508320-c0f7-42a2-9d9f-bbcafff5ac5e)


I have been getting sync issues since last 2 days, please help!!!
