### ISSUE TITLE
Add lintcode support

### ISSUE THREAD

**Issue by JaideepGuntupalli** [arunbhardwaj/LeetHub-2.0#2]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
I am frustrated to manually upload my lintcode solutions.

**Describe the solution you'd like**
Like my leetcode solution is being synced. It would be great if lintcode solutions can be synced as well.

**Describe alternatives you've considered**
The alternative to this is manually uploading your solutions which is boring.

**Additional context**
Lintcode contains a few of the premium questions for leetcode so that's great we could also sync.

Link:
https://www.lintcode.com/

**Comment by arunbhardwaj** [comment]
Unfortunately, this is out of scope for this extension as I only intend to keep this functional for LeetCode and gfg.
