### ISSUE TITLE
Update link in about section

### ISSUE THREAD

**Issue by venkateshmicro98** [arunbhardwaj/LeetHub-2.0#22]
![image](https://github.com/arunbhardwaj/LeetHub-2.0/assets/31404179/4d1eab4d-1f33-4c69-914d-0bed88320e09)
This link still points to old leetcode extension

**Comment by KartikeyBartwal** [comment]
taking on the issue

**Comment by venkateshmicro98** [comment]
Visit https://github.com/arunbhardwaj/LeetHub-2.0.
See the right end of the repo
![image](https://github.com/arunbhardwaj/LeetHub-2.0/assets/31404179/995720d4-25b1-4935-9aea-3d1031158fee)

**Comment by arunbhardwaj** [comment]
Thank you, it's been updated.
