### ISSUE TITLE
No longer pushes code from resubmissions

### ISSUE THREAD

**Issue by bjpfox** [arunbhardwaj/LeetHub-2.0#32]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
Previously when a LeetCode solution was resubmitted, the LeetHub extension would push the revised code to the repo and update the stats accordingly. This no longer seems to work. 

**To Reproduce**
Submit a LeetCode solution.
Make some changes to the code (e.g. remove unnecessary comments)
Resubmit your new solution. 
Check GitHub repo and note that the new code has not been pushed. 

**Expected behavior**
Expect LeetHub to push the revised code to the repo, and to update the commit message based on the new space/time complexity statistics.

**Screenshots**

**Additional context**

**Comment by arunbhardwaj** [comment]
I attempted to reproduce and I got the intended behavior. Are you still experiencing this issue?

![Screenshot 2023-09-18 175251](https://github.com/arunbhardwaj/LeetHub-2.0/assets/20329282/4d595911-4b70-43d5-9d02-cf01c7607f36)
![Screenshot 2023-09-18 175449](https://github.com/arunbhardwaj/LeetHub-2.0/assets/20329282/17241c58-4474-4983-a775-706a47165e19)

**Comment by bjpfox** [comment]
I am now getting the intended behaviour. This issue can be closed.
