### ISSUE TITLE
Feature Request: Manually sync specific submission

### ISSUE THREAD

**Issue by StokerBR** [arunbhardwaj/LeetHub-2.0#71]
**Is your feature request related to a problem? Please describe.**
Yes, sometimes the extension doesn't automatically sync when the code is submitted and approved.

**Describe the solution you'd like**
I'd like for us to be able to manually sync the currently opened submission, by clicking a button [that was injected] on the submission page or on the extension popup when on a submission page for example.

**Additional context**
It would be useful if, for example, I wanted to sync an older submission of a problem (made before installing the LeetHub extension), or that was made on another computer where I don't have the extension, or simply because it didn't sync automatically.
All the information needed (stats, code, language) is on the submission page, and the description is also still there (just its tab that is hidden with display none).

**Example of a possible sync button on submission page**
![image](https://github.com/arunbhardwaj/LeetHub-2.0/assets/51726192/4c949e20-f734-4655-a232-03f4b161cf0f)

**Comment by arunbhardwaj** [comment]
@StokerBR I loved the look of the button so much that I had to implement this feature. Thank you for your effort on the design and mockup. I've implemented this in PR #81 as a beta feature. Please let me know how it works for you!

**Comment by StokerBR** [comment]
I just tested it and it works perfectly, exactly as I wanted! Thanks for implementing this feature and for all the work on the extension.
