### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by mrdinesh-kushwaha** [arunbhardwaj/LeetHub-2.0#73]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mrdinesh-kushwaha** [comment]
I solved Leetcode Problem But Update in my GitHub Account

**Comment by ramnaresh8** [comment]
Yes, happens same with me and the problems are not updating on leetcode
