### ISSUE TITLE
ADD OPTION TO INCLUDE PREVIOUSLY SOLVED[BEFORE THIS EXTENSION] PROBLEMS

### ISSUE THREAD

**Issue by RootProgrammer** [arunbhardwaj/LeetHub-2.0#82]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Is your feature request related to a problem? Please describe.**
- many of us solved a lot of problems before using this extension. if I try to resubmit those problems, that is not included in the list of this extension.
- to get total counting, do something to add old problems to the list

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by arunbhardwaj** [comment]
@RootProgrammer thank you for the ticket. LeetHub `v2.0.5` (will be deployed shortly) will introduce a beta feature to manually submit your previous solutions by going to the respective submission page and clicking a button. This should help you resubmit those older problems. You can preview what it looks like [here](https://github.com/arunbhardwaj/LeetHub-2.0/pull/81). 

As for a total count, unfortunately right now developing a reliable single source of truth for tracking the count of all submitted solutions will take longer than I currently have time for. However, there may be something I can do to get there in the short term but I can't guarantee anything on that front at this time. 

I'll keep this ticket open to notify you once `v2.0.5` gets deployed and then close it.

**Comment by arunbhardwaj** [comment]
@RootProgrammer the manual submission feature is deployed. You should be able to submit any previous submission by navigating to a problems submissions page and viewing any submission. It's currently a beta feature so you may encounter some bugs. Let me know if you have any issues with it via another ticket!

**Comment by RootProgrammer** [comment]
@arunbhardwaj That was quick! Thanks a lot. I'll get back to you shortly right after checking the new feature.

Take Love
ZamaaN

**Comment by NamesMark** [comment]
Awesome feature, huge thanks for implementing! @arunbhardwaj ❤️
